apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dev-app-rollout
spec:
  replicas: 1
  strategy:
    blueGreen: 
      activeService: dev-service
      previewService: dev-preview-service
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: web
        image: placeholder-image
        ports:
        - containerPort: 80