apiVersion: v1
kind: Service
metadata:
  name: web-service-prod
  namespace: prod
spec:
  selector:
    app: web-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer