apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: prod-app-rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {duration: 1m}
      - setWeight: 50
      - pause: {duration: 1m}
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: web
        image: placeholder-image
        ports:
        - containerPort: 80